const MODULE_KEY='keris_module1_260621_v1';
const STEPS=[
 {id:'q1',no:1,title:'번역 결과 역번역으로 검증하기',type:'기능형',area:'B. AI활용',sub:'B1. AI 기반 정보 탐색과 평가',perf:'B1-2',desc:'AI 번역 결과를 역번역으로 확인하고 요청을 더 구체화합니다.'},
 {id:'q2',no:2,title:'교류 활동에 어울리는 그림 만들기',type:'기능형',area:'B. AI활용',sub:'B2. AI 기반 산출물 생성 및 개선',perf:'B2-2',desc:'목적에 맞는 생성 조건을 선택하고 결과 후보를 판단합니다.'},
 {id:'q3',no:3,title:'사진 속 불필요한 요소 제거와 분위기 조정',type:'기능형',area:'B. AI활용',sub:'B2. AI 기반 산출물 생성 및 개선',perf:'B2-3',desc:'필요한 요소는 남기고 불필요한 요소만 제거한 뒤 분위기를 조정합니다.'},
 {id:'q4',no:4,title:'AI 생성 동영상의 사회적 영향 판단하기',type:'선다형',area:'C. AI윤리',sub:'C1. AI의 사회적 영향',perf:'C1-1',desc:'AI 산출물이 친구 관계와 문화 이해에 미칠 영향을 판단합니다.'},
 {id:'q5',no:5,title:'공유 전 윤리 점검하기',type:'선다형',area:'C. AI윤리',sub:'C2. AI윤리와 책임',perf:'C2-3',desc:'개인정보, 동의, AI 생성 표시, 공유 범위를 점검합니다.'}
];
function baseState(){return{q1:{done:false,actions:[],story:'지수는 번역 결과가 원래 뜻을 잘 담고 있는지 확인하려고 합니다.',copied:false,sw1:'Karibu shuleni kwetu.',back1:'',input:'우리 학교에 온 것을 환영해요.',sw2:'',back2:'',word:''},q2:{done:false,actions:[],story:'지수는 실제 얼굴이나 읽을 수 있는 글자 없이 따뜻한 교실 분위기의 그림을 만들고 싶어 합니다.',conds:[],generated:false,result:''},q3:{done:false,actions:[],story:'지수는 전화번호 안내문과 캔만 지우고 친구 얼굴과 환영 카드는 남기고 싶어 합니다.',tool:'',mask:[],removed:false,result:'',kept:false,warm:20,applied:false,snapshot:''},q4:{done:false,actions:[],story:'AI가 만든 동영상이 친구 관계와 문화 이해에 어떤 영향을 줄지 판단해야 합니다.',choices:[]},q5:{done:false,actions:[],story:'완성한 자료를 공유하기 전 안전하고 책임 있는 공유 조건을 점검해야 합니다.',choices:[]}}}
let S=loadState();
function loadState(){try{return JSON.parse(localStorage.getItem(MODULE_KEY))||baseState()}catch(e){return baseState()}}
function save(){localStorage.setItem(MODULE_KEY,JSON.stringify(S))}
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function current(){return location.hash.replace(/^#\/?/,'')||'index'}
function stepById(id){return STEPS.find(s=>s.id===id)}
function log(id,text,story){S[id].actions.push(text);if(story)S[id].story=story;save();render()}
function resetOne(id){S[id]=baseState()[id];save();render()}
function resetAll(){S=baseState();save();render()}
function submitStep(id){S[id].done=true;if(id==='q3')S[id].snapshot=`제출 상태: 결과=${S[id].result||'미선택'}, 따뜻함=${S[id].warm}, 적용=${S[id].applied?'완료':'미완료'}`;log(id,'문항 제출','제출되었습니다. 현재까지의 응답이 저장되었습니다.')}
function renderSidebar(){const side=$('#side'),cur=current(),done=STEPS.filter(s=>S[s.id].done).length;side.innerHTML=`<aside class="sidebar"><div class="brand"><div class="logo">AI</div><div><h1>AI와 함께 준비하는 우리 반 교류 활동</h1><p>초등 AI 리터러시 · 모듈 1</p></div></div><div class="info"><div><span>유형</span><b>개인 과제</b></div><div><span>문항수</span><b>5개</b></div><div><span>예상 시간</span><b>25분</b></div></div><div class="progressTxt"><span>완료</span><span>${done}/5</span></div><div class="bar"><i style="width:${done/5*100}%"></i></div><nav class="nav"><a href="#/index" class="${cur==='index'?'active':''}"><span class="bubbleNo">ⓘ</span><span><span class="navTitle">시나리오</span><span class="navSub">공통 상황</span></span></a>${STEPS.map(s=>`<a href="#/${s.id}" class="${cur===s.id?'active ':''}${S[s.id].done?'done':''}"><span class="bubbleNo">${s.no}</span><span><span class="navTitle">${s.title}</span><span class="navSub">${s.type} · ${s.perf}</span></span></a>`).join('')}</nav><button class="btn warn block" onclick="resetAll()">전체 초기화</button></aside>`}
function pageShell(step,body){const id=step.id,prev=step.no===1?'#/index':`#/${STEPS[step.no-2].id}`,next=step.no===5?'#/index':`#/${STEPS[step.no].id}`;return `<section class="module"><div class="modHead"><div><h2>${step.no}단계. ${step.title}</h2><p>${step.desc}</p><div class="badges"><span>${step.area}</span><span>${step.sub}</span><span>성취수행 ${step.perf}</span></div></div><div class="status ${S[id].done?'ok':''}">${S[id].done?'제출 완료':'진행 중'}</div></div>${body}<div class="story"><div class="avatar">지수</div><div>${S[id].story}</div></div>${S[id].done?'<div class="submitted">제출되었습니다.</div>':''}<div class="logBox"><h3>누른 행동 기록</h3>${S[id].actions.length?`<ol>${S[id].actions.map(a=>`<li>${esc(a)}</li>`).join('')}</ol>`:'<p class="empty">아직 누른 행동이 없습니다.</p>'}</div>${debugBlock(id)}<div class="nextRow"><a class="btn" href="${prev}">이전</a><button class="btn warn" onclick="resetOne('${id}')">이 문제 다시 풀기</button><button class="btn primary" onclick="submitStep('${id}')">문항 제출</button>${S[id].done?`<a class="btn primary" href="${next}">제출하고 이동하기</a>`:''}</div></section>`}
function debugBlock(id){return `<pre class="debug">${esc(JSON.stringify(S[id],null,2))}</pre>`}
function esc(t){return String(t).replace(/[<>&]/g,m=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[m]))}
function deviceBar(name,chip=''){return `<div class="deviceBar"><div class="dots"><i></i><i></i><i></i></div><div class="appName">${name}${chip?`<span class="appChip">${chip}</span>`:''}</div></div>`}
function indexPage(){return `<section class="hero"><div class="heroText"><p class="eyebrow">모듈 1 · 개인 과제 · 25분</p><h1>AI와 함께 준비하는 우리 반 교류 활동</h1><p>지수네 반은 다른 나라 친구들과 온라인 교류 활동을 준비하고 있습니다. 지수는 AI 도구를 활용해 친구들에게 보여 줄 문장, 그림, 사진을 만들고 공유하려고 합니다.</p><p>AI 도구를 활용해 우리 반 교류 활동을 잘 준비하려면 어떻게 해야 할까요?</p><a class="btn primary" href="#/q1">다음으로</a></div><div class="heroIllust"><div class="laptop"><div class="screenGrid"><span>AI 번역</span><span>그림 생성</span><span>사진 편집</span><span>공유 점검</span></div></div><div class="callout">온라인 교류 친구들과 함께 볼 자료를 준비해요.</div></div></section><section class="module"><h2>문항 구성</h2><div class="stepTable">${STEPS.map(s=>`<a href="#/${s.id}"><b>${s.no}단계</b><span>${s.title}</span><em>${s.type} · ${s.perf}</em></a>`).join('')}</div></section>`}
function q1(){const s=S.q1;const words=s.sw2?['Karibu','Shuleni','kwetu','rafiki yangu']:[];const body=`<div class="talk"><b>상황</b><p>지수는 다른 나라 친구들에게 보여 줄 환영 문장을 AI 번역 도구로 스와힐리어로 번역하려고 합니다. 번역 결과가 원래 뜻을 잘 담고 있는지 확인하고, 더 알맞은 스와힐리어 번역을 선택하세요.</p></div><div class="toolGrid"><div class="device translate">${deviceBar('AI 번역 도구','스와힐리어')}<div class="translateTop"><button class="langBtn">한국어</button><button class="swapBtn" onclick="S.q1.back1='저희 학교에 오신 것을 환영합니다.';log('q1','언어전환 버튼 클릭','역번역 결과에서 원래 표현과 달라진 부분을 확인했습니다.')">⇄</button><button class="langBtn">스와힐리어</button></div><div class="panes"><div class="pane"><label>한국어 입력문</label><textarea id="q1input" oninput="S.q1.input=this.value;save()">${esc(s.input)}</textarea><button class="btn small" onclick="S.q1.input='친구야, 우리 학교에 온 것을 환영해요.';S.q1.sw2='Karibu shuleni kwetu, rafiki yangu.';log('q1','한국어 입력문에 친구야 표현 추가','요청이 더 구체화되어 새 번역 결과가 만들어졌습니다.')">친구야 표현 추가</button></div><div class="pane"><label>스와힐리어 번역</label><div class="resultText">${esc(s.sw2||s.sw1)}</div><button class="btn small" onclick="S.q1.copied=true;log('q1','번역 복사 버튼 클릭','처음 생성된 번역을 비교 자료로 남겼습니다.')">번역 복사</button><button class="btn small" onclick="if(S.q1.sw2){S.q1.back2='친구야, 우리 학교에 온 것을 환영해요.';log('q1','수정 후 언어전환 버튼 클릭','수정된 번역을 다시 한국어로 확인했습니다.')}else{S.q1.back1='저희 학교에 오신 것을 환영합니다.';log('q1','언어전환 버튼 클릭','역번역 결과가 나타났습니다.')}}">다시 한국어로 확인</button></div></div><div class="backBox"><b>역번역 결과</b><p>${esc(s.back2||s.back1||'아직 확인하지 않았습니다.')}</p></div></div><div class="panel"><h3>단어 확인</h3><p class="mini">수정 후 생성된 문장에서 ‘친구’에 해당하는 표현을 고르세요.</p><div class="wordBox">${words.length?words.map(w=>`<button class="word ${s.word===w?'selected':''}" onclick="S.q1.word='${w}';log('q1','단어 선택: ${w}','스와힐리어 문장 안에서 의미가 반영된 표현을 골랐습니다.')">${w}</button>`).join(''):'<p class="empty">한국어 입력문을 수정하면 단어 선택지가 나타납니다.</p>'}</div></div></div>`;$('#main').innerHTML=pageShell(STEPS[0],body)}
function q2(){const s=S.q2,good=['따뜻한 종이 콜라주','실제 얼굴 없음','글자 없음','정사각형','교실 환영 분위기'],bad=['큰 국기와 민족 의상 강조','실제 학생 사진처럼'];const btn=o=>`<button class="condition ${s.conds.includes(o)?'selected':''}" onclick="toggleCond('${o.replace(/'/g,"\\'")}')">${o}</button>`;const results=s.generated?`<div class="resultCards"><button class="resultCard ${s.result==='r1'?'selected':''}" onclick="S.q2.result='r1';log('q2','결과 1 선택','실제 얼굴처럼 보이는 인물과 깨진 글자가 포함된 후보를 선택했습니다.')"><div class="thumb faceText">WELC0M</div><b>결과 1</b><span>얼굴과 깨진 글자 포함</span></button><button class="resultCard ${s.result==='r2'?'selected':''}" onclick="S.q2.result='r2';log('q2','결과 2 선택','실제 얼굴이나 읽을 수 있는 글자 없이 따뜻한 교실 분위기가 드러나는 후보를 선택했습니다.')"><div class="thumb warmRoom"></div><b>결과 2</b><span>따뜻한 교실 분위기</span></button><button class="resultCard ${s.result==='r3'?'selected':''}" onclick="S.q2.result='r3';log('q2','결과 3 선택','특정 나라 이미지가 강하게 강조된 후보를 선택했습니다.')"><div class="thumb flagOnly"></div><b>결과 3</b><span>국기와 상징 강조</span></button></div>`:'<p class="empty">조건을 선택하고 그림 생성 버튼을 누르면 결과 후보가 나타납니다.</p>';const body=`<div class="talk"><b>상황</b><p>지수는 다른 나라 친구들과의 교류 활동에 어울리는 그림을 AI 동영상 생성 도구로 만들려고 합니다. 실제 친구 얼굴이나 읽을 수 있는 글자는 넣지 않고, 따뜻한 교실 분위기가 드러나는 그림을 생성하세요.</p></div><div class="toolGrid"><div class="device">${deviceBar('AI 동영상 생성 도구','그림 생성')}<div class="promptBox"><b>프롬프트</b><p>환영 앨범 표지 배경${s.conds.length?', '+s.conds.join(', '):''}</p></div><div class="conditionBox">${good.map(btn).join('')}${bad.map(btn).join('')}</div><button class="btn primary" onclick="S.q2.generated=true;log('q2','그림 생성 버튼 클릭','선택한 조건으로 세 개의 후보가 생성되었습니다.')">그림 생성</button></div><div class="panel"><h3>생성 결과 후보</h3>${results}</div></div>`;$('#main').innerHTML=pageShell(STEPS[1],body)}
function toggleCond(o){const a=S.q2.conds;if(a.includes(o))S.q2.conds=a.filter(x=>x!==o);else a.push(o);log('q2','조건 선택: '+o,conditionStory(o))}
function conditionStory(o){return {'따뜻한 종이 콜라주':'따뜻한 교실 분위기를 만들 수 있는 스타일 조건을 추가했습니다.','실제 얼굴 없음':'실제 친구 얼굴이 나오지 않도록 조건을 추가했습니다.','글자 없음':'AI가 깨진 글자를 만들지 않도록 조건을 추가했습니다.','정사각형':'앨범 표지에 맞는 비율 조건을 추가했습니다.','교실 환영 분위기':'교류 활동 맥락이 드러나도록 조건을 추가했습니다.'}[o]||'선택한 조건이 교류 활동 목적에 맞는지 다시 판단해야 합니다.'}
function q3(){const s=S.q3;const photo=`<div id="photo" class="photo" style="--warm:${s.warm/100}"><div class="person ${s.mask.includes('face')?'marked':''}" onclick="markArea('face')"><span>친구 얼굴</span></div><div class="welcome ${s.mask.includes('card')?'marked':''}" onclick="markArea('card')">WELCOME</div><div class="notice ${s.mask.includes('notice')?'marked':''} ${(s.result==='r3'||s.result==='r1')?'gone':''}" onclick="markArea('notice')">연락처<br>010-1234</div><div class="can ${s.mask.includes('can')?'marked':''} ${s.result==='r3'?'gone':''}" onclick="markArea('can')"></div></div>`;const result=s.removed?`<div class="resultList"><button class="resultLine ${s.result==='r1'?'selected':''}" onclick="S.q3.result='r1';log('q3','결과 1 선택','전화번호와 캔은 사라졌지만 친구 얼굴이 어색하게 변한 결과를 선택했습니다.')">결과 1 · 얼굴이 어색하게 변함</button><button class="resultLine ${s.result==='r2'?'selected':''}" onclick="S.q3.result='r2';log('q3','결과 2 선택','전화번호는 사라졌지만 캔이 남아 있는 결과를 선택했습니다.')">결과 2 · 캔이 남아 있음</button><button class="resultLine ${s.result==='r3'?'selected':''}" onclick="S.q3.result='r3';log('q3','결과 3 선택','전화번호와 캔이 사라지고 친구 얼굴과 환영 카드가 유지된 결과를 선택했습니다.')">결과 3 · 필요한 것만 제거됨</button><button class="btn primary" onclick="S.q3.kept=true;log('q3','유지 버튼 클릭','선택한 결과가 작업 화면에 반영되었습니다.')">유지</button></div>`:'';const adjust=s.tool==='adjust'?`<div class="adjust"><label>따뜻함 <b>${s.warm}</b></label><input type="range" min="0" max="100" value="${s.warm}" oninput="S.q3.warm=Number(this.value);save();$('#photo').style.setProperty('--warm',S.q3.warm/100);$('.adjust b').textContent=S.q3.warm"><button class="btn primary" onclick="S.q3.applied=true;log('q3','적용 버튼 클릭','현재 색감 상태가 사진에 적용되었습니다.')">적용</button></div>`:'';const body=`<div class="talk"><b>상황</b><p>사진에서 필요 없는 물건과 개인정보가 보이는 안내문은 지우고, 친구 얼굴과 환영 카드는 그대로 남긴 뒤 사진 분위기를 따뜻하게 조정하세요.</p></div><div class="editGrid"><div class="device">${deviceBar('AI 사진 편집 도구','사진 편집')}<div class="stage">${photo}</div></div><div class="sidePanel"><button class="toolBtn" onclick="S.q3.tool='crop';log('q3','자르기 버튼 클릭','사진을 자르는 도구를 선택했습니다.')">자르기</button><button class="toolBtn" onclick="S.q3.tool='adjust';log('q3','조정 버튼 클릭','따뜻함을 조절할 수 있는 기능이 열렸습니다.')">조정</button><button class="toolBtn" onclick="S.q3.tool='removeBg';log('q3','배경 제거 버튼 클릭','배경 전체를 지우는 도구를 선택했습니다.')">배경 제거</button><button class="toolBtn primary" onclick="S.q3.tool='remove';log('q3','개체 제거 버튼 클릭','사진 속에서 없앨 영역만 선택할 수 있습니다.')">개체 제거</button><button class="btn primary block" onclick="S.q3.removed=true;log('q3','제거 버튼 클릭','AI 개체 제거 결과 후보가 나타났습니다.')">제거</button>${result}${adjust}${s.snapshot?`<div class="snapshot">${esc(s.snapshot)}</div>`:''}</div></div>`;$('#main').innerHTML=pageShell(STEPS[2],body)}
function markArea(a){if(S.q3.tool!=='remove'){log('q3','도구 선택 없이 영역 클릭: '+areaName(a),'먼저 개체 제거 도구를 선택해야 영역을 지울 수 있습니다.');return}const m=S.q3.mask;if(m.includes(a))S.q3.mask=m.filter(x=>x!==a);else m.push(a);log('q3','영역 선택: '+areaName(a),['notice','can'].includes(a)?'없애야 할 영역을 선택했습니다.':'남겨야 할 영역도 선택될 수 있으므로 주의가 필요합니다.')}
function areaName(a){return {notice:'전화번호 안내문',can:'캔',face:'친구 얼굴',card:'환영 카드'}[a]||a}
function q4(){const s=S.q4,items=[['1','동영상이 예쁘면 친구들이 어떤 느낌을 받을지는 생각하지 않아도 된다.'],['2','특정 나라나 문화를 한 가지 모습으로만 표현하면 친구들이 그 문화를 단순하게 이해할 수 있다.'],['3','AI 동영상이 친구나 문화의 모습을 어색하게 표현하면 교류 친구가 불편하게 느낄 수 있다.'],['4','AI가 만든 동영상은 사람이 만든 자료가 아니므로 교류 활동이나 친구 관계에 영향을 주지 않는다.'],['5','여러 문화와 친구의 모습을 존중하는 표현인지 확인해야 한다.']];const body=`<div class="talk"><b>상황</b><p>AI가 만든 교류 활동 동영상을 교류 자료로 사용할 때 친구 관계나 문화 이해에 어떤 영향을 줄 수 있는지 생각해 보세요.</p></div><div class="choiceGrid"><div class="shorts"><div class="videoMock"><div class="flagLarge"></div><div class="personRow"><i></i><i></i><i></i></div><p>친구들이 이 동영상을 보면 어떤 생각을 하게 될까?</p></div></div><div class="choices"><h3>알맞은 것을 모두 고르세요.</h3>${items.map(([k,t])=>`<label class="choice ${s.choices.includes(k)?'selected':''}"><input type="checkbox" ${s.choices.includes(k)?'checked':''} onchange="toggleChoice('q4','${k}')"> ${k}. ${t}</label>`).join('')}</div></div>`;$('#main').innerHTML=pageShell(STEPS[3],body)}
function q5(){const s=S.q5,items=[['1','친구 사진을 사용해도 되는지 동의를 확인한다.'],['2','사진이나 자료에 전화번호, 이름표 등 개인정보가 보이지 않는지 확인한다.'],['3','AI로 만든 그림이 포함되어 있음을 표시한다.'],['4','자료를 빨리 보여 주기 위해 먼저 전체 공개로 공유한다.'],['5','필요한 사람만 볼 수 있도록 공유 범위를 설정한다.']];const body=`<div class="talk"><b>상황</b><p>완성한 교류 활동 자료를 온라인으로 공유하기 전에 친구 사진 사용 동의, 개인정보, AI 생성 표시, 공유 범위를 점검하세요.</p></div><div class="choiceGrid"><div class="uploadMock"><div class="postPreview"><b>교류 활동 앨범</b><p>AI 그림 · 친구 사진 · 번역 문장 포함</p><span>공유 설정: 전체 공개</span><span>AI 생성 표시: 없음</span><span>동의 확인: 필요</span></div></div><div class="choices"><h3>해야 할 행동을 모두 고르세요.</h3>${items.map(([k,t])=>`<label class="choice ${s.choices.includes(k)?'selected':''}"><input type="checkbox" ${s.choices.includes(k)?'checked':''} onchange="toggleChoice('q5','${k}')"> ${k}. ${t}</label>`).join('')}</div></div>`;$('#main').innerHTML=pageShell(STEPS[4],body)}
function toggleChoice(id,k){const c=S[id].choices;if(c.includes(k))S[id].choices=c.filter(x=>x!==k);else c.push(k);log(id,'선택지 '+k+'번 '+(S[id].choices.includes(k)?'선택':'해제'),'선택한 항목이 기록되었습니다.')}
function route(){renderSidebar();const id=current();if(id==='q1')q1();else if(id==='q2')q2();else if(id==='q3')q3();else if(id==='q4')q4();else if(id==='q5')q5();else $('#main').innerHTML=indexPage()}
window.addEventListener('hashchange',route);route();
function selftest(){try{['q1','q2','q3','q4','q5'].forEach(id=>{location.hash='#/'+id;route();if(!$('#main').textContent.includes(stepById(id).title))throw new Error(id)});document.body.dataset.selftest='all pass'}catch(e){document.body.dataset.selftest='fail '+e.message}}
if(location.search.includes('selftest'))setTimeout(selftest,50);
