/* HWP item-card patch: branded 5-step screen flow */
function patchState(id){ if(!S[id].screen) S[id].screen=1; return S[id]; }
function screenTabsPatch(st){const s=patchState(st.id),n=st.id==='q3'?4:(st.id==='q4'||st.id==='q5'?1:3);return `<div class="screenTabs">${Array.from({length:n},(_,i)=>`<span class="${s.screen===i+1?'now':''}">화면 ${i+1}</span>`).join('')}</div>`}
function shellPatch(st,body){const id=st.id,prev=st.no===1?'#/index':`#/${STEPS[st.no-2].id}`,next=st.no===5?'#/index':`#/${STEPS[st.no].id}`;main.innerHTML=`<section class="module"><div class="modHead"><div><h2>${st.no}단계. ${st.title}</h2><p>${appName(id)} 화면을 본뜬 평가용 화면입니다.</p><div class="badges"><span>${st.area}</span><span>${st.type||'문항'}</span><span>성취수행 ${st.perf}</span></div></div><div class="status ${S[id].done?'ok':''}">${S[id].done?'제출 완료':'진행 중'}</div></div>${screenTabsPatch(st)}${body}<div class="story"><div class="avatar">지수</div><div>${S[id].story}</div></div>${S[id].done?'<div class="submitted">제출되었습니다.</div>':''}<div class="logBox"><h3>누른 행동 기록</h3>${S[id].actions?.length?`<ol>${S[id].actions.map(a=>`<li>${esc(a)}</li>`).join('')}</ol>`:'<p class="empty">아직 누른 행동이 없습니다.</p>'}</div>${debugBlock(id)}<div class="nextRow"><a class="btn" href="${prev}">이전</a><button class="btn warn" onclick="resetOne('${id}')">이 문제 다시 풀기</button><button class="btn primary" onclick="submitStep('${id}')">문항 제출</button>${S[id].done?`<a class="btn primary" href="${next}">제출하고 이동하기</a>`:''}</div></section>`}
function appName(id){return {q1:'Google 번역',q2:'Canva',q3:'Adobe Express',q4:'YouTube Shorts',q5:'Instagram'}[id]}
function q1(){const st=STEPS[0],s=patchState('q1');if(!s.sw1)s.sw1='Karibu shuleni kwetu.';let src=s.screen===1?'우리 학교에 온 것을 환영해요.':(s.input||'우리 학교에 온 것을 환영해요.'),target=s.screen===3?(s.sw2||'Karibu shuleni kwetu, rafiki yangu.'):s.sw1;let side=s.screen===1?`<div class="taskCard"><h3>화면 1</h3><p>처음 번역 결과를 Google 번역의 언어 전환 버튼으로 다시 한국어로 확인하고, 번역 복사 버튼으로 기록합니다.</p><p class="mini">정답 행동: 언어 전환(⇄), 번역 복사</p></div>`:s.screen===2?`<div class="taskCard"><h3>화면 2</h3><p>한국어 입력문에 ‘친구야’를 추가한 뒤 같은 언어 전환 버튼을 다시 누릅니다.</p><p class="mini">정답 행동: 한국어 입력문 수정, 언어 전환(⇄)</p></div>`:`<div class="taskCard"><h3>화면 3</h3><p>새 스와힐리어 문장에서 ‘친구’에 해당하는 표현을 고릅니다.</p><div class="wordRow">${['Karibu','shuleni','kwetu','rafiki yangu'].map(w=>`<button class="word ${s.word===w?'selected':''}" onclick="q1WordPatch('${w}')">${w}</button>`).join('')}</div></div>`;let body=`<div class="toolGrid"><div class="googleBox"><div class="gHeader"><div class="gLogo"><b>G</b>oogle 번역</div><div>☰ ⋮</div></div><div class="gLangs"><button>한국어</button><button class="gSwap" onclick="q1SwapPatch()">⇄</button><button>스와힐리어</button></div><div class="gPanels"><div class="gPanel"><div class="gLabel">원문</div><textarea ${s.screen===1?'readonly':''} oninput="S.q1.input=this.value;save()">${esc(src)}</textarea>${s.screen>=2?'<button class="btn small" onclick="q1AddFriendPatch()">‘친구야’ 표현 추가</button>':''}</div><div class="gPanel"><div class="gLabel">번역</div><div class="gOutput">${esc(target)}</div><div class="gTools"><button onclick="q1SwapPatch()" title="언어 전환">⇄</button><button onclick="q1CopyPatch()" title="번역 복사">⧉</button><button title="듣기">🔊</button></div></div></div>${s.back1||s.back2?`<div class="backResult"><b>다시 한국어로 확인한 결과</b><p>${esc(s.back2||s.back1)}</p></div>`:''}</div>${side}</div>`;shellPatch(st,body)}
function q1SwapPatch(){const s=patchState('q1');if(s.screen===1){s.swap1=true;s.back1='저희 학교에 오신 것을 환영합니다.';if(s.copied)s.screen=2;log('q1','언어 전환 버튼 클릭','역번역 결과에서 표현이 조금 달라진 것을 확인했습니다.')}else if(s.screen===2){s.sw2='Karibu shuleni kwetu, rafiki yangu.';s.back2='친구야, 우리 학교에 온 것을 환영해요.';s.screen=3;log('q1','수정 후 언어 전환 버튼 클릭','수정한 문장을 다시 번역하고 한국어로 확인했습니다.')}else log('q1','언어 전환 버튼 클릭','이미 수정 후 번역 결과를 확인한 상태입니다.')}
function q1CopyPatch(){const s=patchState('q1');s.copied=true;if(s.swap1)s.screen=2;log('q1','번역 복사 버튼 클릭','처음 스와힐리어 번역을 비교 자료로 복사했습니다.')}
function q1AddFriendPatch(){const s=patchState('q1');s.input='친구야, 우리 학교에 온 것을 환영해요.';log('q1','한국어 입력문에 ‘친구야’ 표현 추가','친구에게 전하는 말이라는 목적이 더 분명해졌습니다.')}
function q1WordPatch(w){S.q1.word=w;log('q1','단어 선택: '+w,w==='rafiki yangu'?'친구 표현을 골랐습니다.':'뜻을 다시 확인해야 하는 표현입니다.')}
const Q2GOOD=['따뜻한 종이 콜라주','실제 얼굴 없음','글자 없음','정사각형','교실 환영 분위기'],Q2BAD=['큰 국기와 민족 의상 강조','실제 학생 사진처럼'];
function q2(){const st=STEPS[1],s=patchState('q2');if(!s.conds)s.conds=[];let main='';if(s.screen===1)main=`<div class="canvaCanvas"><h3>AI 동영상 생성 조건</h3><div class="conditionGrid">${[...Q2GOOD,...Q2BAD].map(c=>`<button class="condition ${s.conds.includes(c)?'selected':''}" onclick="q2CondPatch('${c}')">${c}</button>`).join('')}</div></div><div class="canvaPanel"><h3>화면 1</h3><p>교류 활동에 맞는 조건을 여러 개 고릅니다.</p><p class="mini">정답 행동: 좋은 조건 5개 선택</p></div>`;if(s.screen===2)main=`<div class="canvaCanvas"><h3>프롬프트</h3><div class="promptBox">환영 앨범 표지 배경, ${s.conds.join(', ')}</div><button class="btn primary" onclick="q2GeneratePatch()">그림 생성</button></div><div class="canvaPanel"><h3>화면 2</h3><p>선택한 조건으로 AI가 그림을 만들도록 합니다.</p><p class="mini">정답 행동: 그림 생성</p></div>`;if(s.screen===3)main=`<div class="canvaCanvas"><h3>생성 결과</h3><div class="canvaResults"><button class="resultCard ${s.result==='r1'?'selected':''}" onclick="q2ResultPatch('r1')"><div class="thumb faceText">WELC0M</div><b>결과 1</b><span>얼굴과 깨진 글자 포함</span></button><button class="resultCard ${s.result==='r2'?'selected':''}" onclick="q2ResultPatch('r2')"><div class="thumb warmRoom"></div><b>결과 2</b><span>따뜻한 교실 분위기</span></button><button class="resultCard ${s.result==='r3'?'selected':''}" onclick="q2ResultPatch('r3')"><div class="thumb flagOnly"></div><b>결과 3</b><span>큰 국기와 상징 강조</span></button></div></div><div class="canvaPanel"><h3>화면 3</h3><p>세 후보 중 교류 활동에 가장 알맞은 그림을 고릅니다.</p><p class="mini">정답 행동: 결과 2</p></div>`;shellPatch(st,`<div class="canva"><div class="canvaTop"><div class="canvaLogo">Canva</div><button>공유</button></div><div class="canvaWork"><div class="canvaRail"><span>디자인</span><span>요소</span><span>텍스트</span><span>앱</span></div>${main}</div></div>`)}
function q2CondPatch(c){const s=patchState('q2');s.conds=s.conds||[];s.conds=s.conds.includes(c)?s.conds.filter(x=>x!==c):[...s.conds,c];if(Q2GOOD.every(x=>s.conds.includes(x)))s.screen=2;log('q2','조건 선택: '+c,Q2GOOD.includes(c)?'상황에 맞는 생성 조건을 추가했습니다.':'조건이 목적에 맞는지 다시 생각해야 합니다.')}
function q2GeneratePatch(){const s=patchState('q2');s.generated=true;s.screen=3;log('q2','그림 생성 버튼 클릭','선택한 조건으로 결과 후보가 생성되었습니다.')}
function q2ResultPatch(r){S.q2.result=r;log('q2','결과 선택: '+r,r==='r2'?'목적과 조건에 가장 맞는 그림을 골랐습니다.':'조건에 맞는지 다시 확인해야 합니다.')}
render();window.addEventListener('hashchange',()=>setTimeout(render,0));
