/* HWP item-card patch: Adobe Express, YouTube Shorts, Instagram */
function patchState2(id){ if(!S[id].screen) S[id].screen=1; return S[id]; }
function photoPatch(){const s=patchState2('q3'),gone=(s.result==='r3'||s.result==='r1'),canGone=s.result==='r3';return `<div id="photo" class="photo" style="--warm:${(s.warm||20)/100}"><div class="person ${s.mask?.includes('face')?'marked':''}" onclick="q3AreaPatch('face')"><span>친구 얼굴</span></div><div class="welcome ${s.mask?.includes('card')?'marked':''}" onclick="q3AreaPatch('card')">WELCOME</div><div class="notice ${s.mask?.includes('notice')?'marked':''} ${gone?'gone':''}" onclick="q3AreaPatch('notice')">연락처<br>010-1234</div><div class="can ${s.mask?.includes('can')?'marked':''} ${canGone?'gone':''}" onclick="q3AreaPatch('can')"></div></div>`}
function q3(){const st=STEPS[2],s=patchState2('q3');if(!s.mask)s.mask=[];let p='';if(s.screen===1)p=`<h3>도구</h3><button onclick="q3ToolPatch('crop')">자르기</button><button onclick="q3ToolPatch('adjust')">조정</button><button onclick="q3ToolPatch('removeBg')">배경 제거</button><button class="primary" onclick="q3ToolPatch('remove')">개체 제거</button><p class="mini">정답 행동: 개체 제거</p>`;if(s.screen===2)p=`<h3>개체 제거</h3><p>없앨 영역만 선택하세요.</p><button class="btn primary block" onclick="q3RemovePatch()">제거</button><p class="mini">정답 행동: 전화번호 안내문, 캔, 제거</p>`;if(s.screen===3)p=`<h3>결과 후보</h3><button class="resultLine ${s.result==='r1'?'selected':''}" onclick="q3ResultPatch('r1')">결과 1 · 얼굴이 어색함</button><button class="resultLine ${s.result==='r2'?'selected':''}" onclick="q3ResultPatch('r2')">결과 2 · 캔이 남아 있음</button><button class="resultLine ${s.result==='r3'?'selected':''}" onclick="q3ResultPatch('r3')">결과 3 · 필요한 것만 제거됨</button><button class="btn primary block" onclick="q3KeepPatch()">유지</button><p class="mini">정답 행동: 결과 3, 유지</p>`;if(s.screen===4)p=`<h3>조정</h3><button onclick="q3OpenPatch()">조정</button>${s.adjustOpened?`<div class="adjust"><label>따뜻함 <b>${s.warm||20}</b></label><input type="range" min="0" max="100" value="${s.warm||20}" oninput="q3WarmPatch(this.value)"><button class="btn primary block" onclick="q3ApplyPatch()">적용</button></div>`:''}${s.snapshot?`<div class="snapshot">${esc(s.snapshot)}</div>`:''}<p class="mini">정답 행동: 조정, 따뜻함 슬라이더, 적용, 문항 제출</p>`;shellPatch(st,`<div class="adobe"><div class="adobeTop"><b>Adobe Express</b><span>다운로드</span></div><div class="adobeWork"><div class="adobeStage">${photoPatch()}</div><div class="adobePanel">${p}</div></div></div>`)}
function q3ToolPatch(t){const s=patchState2('q3');s.tool=t;if(t==='remove')s.screen=2;log('q3',(t==='remove'?'개체 제거':t==='adjust'?'조정':t==='removeBg'?'배경 제거':'자르기')+' 버튼 클릭',t==='remove'?'개체 제거 도구가 열렸습니다.':'과제 조건에 맞는 도구인지 다시 생각해야 합니다.')}
function q3AreaPatch(a){const s=patchState2('q3');if(s.tool!=='remove'){log('q3','도구 없이 영역 클릭','먼저 개체 제거 도구를 선택해야 합니다.');return}s.mask=s.mask||[];s.mask=s.mask.includes(a)?s.mask.filter(x=>x!==a):[...s.mask,a];log('q3','영역 선택: '+({notice:'전화번호 안내문',can:'캔',face:'친구 얼굴',card:'환영 카드'}[a]),['notice','can'].includes(a)?'없애야 할 영역을 선택했습니다.':'보존해야 할 영역입니다.')}
function q3RemovePatch(){const s=patchState2('q3');s.removed=true;s.screen=3;log('q3','제거 버튼 클릭','AI 개체 제거 결과 후보가 나타났습니다.')}
function q3ResultPatch(r){S.q3.result=r;log('q3','결과 선택: '+r,r==='r3'?'필요한 것만 제거된 결과입니다.':'결과가 조건을 모두 만족하는지 확인해야 합니다.')}
function q3KeepPatch(){const s=patchState2('q3');s.kept=true;s.screen=4;log('q3','유지 버튼 클릭','선택한 결과가 작업 화면에 반영되었습니다.')}
function q3OpenPatch(){S.q3.adjustOpened=true;log('q3','조정 버튼 클릭','따뜻함 슬라이더가 열렸습니다.')}
function q3WarmPatch(v){S.q3.warm=Number(v);save();$('#photo').style.setProperty('--warm',S.q3.warm/100);$('.adjust b').textContent=S.q3.warm;S.q3.actions.push('따뜻함 슬라이더 조정: '+S.q3.warm);S.q3.story='사진 색감이 실제로 바뀌었습니다.';save();render()}
function q3ApplyPatch(){S.q3.applied=true;log('q3','적용 버튼 클릭','현재 사진 상태가 적용되었습니다.')}
function q4(){const st=STEPS[3],s=patchState2('q4'),it=[['1','동영상이 예쁘면 친구들이 어떤 느낌을 받을지는 생각하지 않아도 된다.'],['2','특정 나라나 문화를 한 가지 모습으로만 표현하면 친구들이 그 문화를 단순하게 이해할 수 있다.'],['3','AI 동영상이 친구나 문화의 모습을 어색하게 표현하면 교류 친구가 불편하게 느낄 수 있다.'],['4','AI가 만든 동영상은 사람이 만든 자료가 아니므로 교류 활동이나 친구 관계에 영향을 주지 않는다.'],['5','여러 문화와 친구의 모습을 존중하는 표현인지 확인해야 한다.']];shellPatch(st,`<div class="shortsWrap"><div class="youtubePhone"><div class="ytTop">YouTube Shorts</div><div class="shortVideo"><div class="flagLarge"></div><div class="personRow"><i></i><i></i><i></i></div><p>친구들이 이 동영상을 보면 어떤 생각을 하게 될까?</p></div><div class="ytActions">♡ 💬 ↗</div></div><div class="choices"><h3>알맞은 것을 모두 고르세요.</h3>${it.map(([k,t])=>`<label class="choice ${s.choices?.includes(k)?'selected':''}"><input type="checkbox" ${s.choices?.includes(k)?'checked':''} onchange="toggleChoice('q4','${k}')"> ${k}. ${t}</label>`).join('')}</div></div>`)}
function q5(){const st=STEPS[4],s=patchState2('q5'),it=[['1','친구 사진을 사용해도 되는지 동의를 확인한다.'],['2','사진이나 자료에 전화번호, 이름표 등 개인정보가 보이지 않는지 확인한다.'],['3','AI로 만든 그림이 포함되어 있음을 표시한다.'],['4','자료를 빨리 보여 주기 위해 먼저 전체 공개로 공유한다.'],['5','필요한 사람만 볼 수 있도록 공유 범위를 설정한다.']];shellPatch(st,`<div class="instaWrap"><div class="insta"><div class="instaTop">Instagram <button>공유</button></div><div class="postPreview"><div class="squarePic"></div><div class="settings"><span>공유 설정: 전체 공개</span><span>AI 생성 표시: 없음</span><span>동의 확인: 필요</span><span>개인정보 확인: 필요</span></div></div></div><div class="choices"><h3>공유 전에 해야 할 행동을 모두 고르세요.</h3>${it.map(([k,t])=>`<label class="choice ${s.choices?.includes(k)?'selected':''}"><input type="checkbox" ${s.choices?.includes(k)?'checked':''} onchange="toggleChoice('q5','${k}')"> ${k}. ${t}</label>`).join('')}</div></div>`)}
render();window.addEventListener('hashchange',()=>setTimeout(render,0));
